<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	<TargetFramework>net10.0-windows</TargetFramework>
	<LangVersion>latest</LangVersion>
	<OutputPath>..\bin\</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	<Nullable>enable</Nullable>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	<UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
	<ApplicationIcon>DiGi.GIS.ico</ApplicationIcon>
  </PropertyGroup>

	<Target Name="CopyFiles" AfterTargets="Build">
		<!-- List files to copy -->
		<ItemGroup Condition="Exists('$(ProjectDir)..\user files\GIS_PostgreSQL_Main.conf')">
			<Files Include="$(ProjectDir)..\user files\GIS_PostgreSQL_Main.conf" />
		</ItemGroup>

		<ItemGroup Condition="Exists('$(ProjectDir)..\user files\GIS_PostgreSQL_Storage.conf')">
			<Files Include="$(ProjectDir)..\user files\GIS_PostgreSQL_Storage.conf" />
		</ItemGroup>

		<!-- Copy them to bin directory -->
		<Copy SourceFiles="@(Files)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
	</Target>

  <ItemGroup>
    <Content Include="DiGi.GIS.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiGi.GIS.PostgreSQL.UI\DiGi.GIS.PostgreSQL.UI.csproj" />
  </ItemGroup>

</Project>
