<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>

		<OutputPath>..\bin\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>false</SelfContained>

		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>

		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

		<ApplicationIcon>Resources\DiGi.GIS.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DiGi.GIS.PostgreSQL.UI\DiGi.GIS.PostgreSQL.UI.csproj" />
	</ItemGroup>

	<Target Name="CopyUserFiles" AfterTargets="Build">
		<ItemGroup>
			<_UserFiles Include="$(ProjectDir)..\user files\**\*.*" />
		</ItemGroup>
		<Message Text="Copying all user files from directory..." Importance="high" />
		<Copy SourceFiles="@(_UserFiles)" DestinationFiles="@(_UserFiles->'$(OutputPath)%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
	</Target>

	<Target Name="ForceCopyAspNetCoreDlls" AfterTargets="ResolveFrameworkReferences">
		<ItemGroup>
			<ResolvedCompileFileDefinitions Update="@(ResolvedCompileFileDefinitions)">
				<CopyLocal>true</CopyLocal>
			</ResolvedCompileFileDefinitions>
		</ItemGroup>
	</Target>
</Project>